### ISSUE TITLE
Error parsing segments in get-params

### ISSUE THREAD

**Issue by Antonio-Laguna** [vordgi/nimpl-getters#56]
Hey @vordgi !

This is a nice package, I wish this was just supported on Next but it isn't! I've got this issue on using `getParams` There are no params to be fetched here but this is for the root layout to be able to set the proper `lang` for `html`

```
urlPathname: `/`;
pagePath: `/(frontend)/(corporate)/page`;
```

This is not a public project so let me know if you need further information

**Comment by vordgi** [comment]
Hi!

Thank you for issue!

There is enough information, thanks - I was able to reproduce it.

_Working on fix!_

**Comment by vordgi** [comment]
@Antonio-Laguna Fixed in v1.3.3!)

Thanks again for writing about the problem!

**Comment by Antonio-Laguna** [comment]
@vordgi thanks for the prompt fix!

**Comment by Antonio-Laguna** [comment]
I have more...

```
urlPathname: `/(.)foo`;
pagePath: `/(frontend)/(.)foo/page`;
```

**Comment by Antonio-Laguna** [comment]
@vordgi let me know if you'd rather have a separate issue!

**Comment by vordgi** [comment]
Yes, I would appreciate a separate issue.

As a urlPathname there should be a path without the intercepted part. Can you please specify in the issue which URL this route for (or which URL is expected for)?
