### ISSUE TITLE
Nextjs 15 support

### ISSUE THREAD

**Issue by ouedyan** [vordgi/nimpl-getters#85]
When using next.js 15 getPathname crashes the app with the following error: 

`Error: Cannot find module 'next/dist/client/components/static-generation-async-storage.external'`

**Comment by vordgi** [comment]
Hello, thanks for the issue, looking into it!

**Comment by ouedyan** [comment]
Also maybe tests need to be updated:
[https://github.com/vordgi/nimpl-getters#stability](https://github.com/vordgi/nimpl-getters#stability)


> All getters are covered with tests. Tests are run on every release and every 6 hours on the latest Canary version of Next.js.
> 
> In this way, you can be sure not only of the stability of the code, but also that if there is a breaking change in Next.js, this will immediately become known. Even before the release of a stable version of Next.js.

**Comment by vordgi** [comment]
- [ ] Update helpers
- [ ] Remove get-search-params
- [ ] Update tests
- [ ] Update docs

**Comment by vordgi** [comment]
_Version 2.0.0-canary.0 has been released. The stable version will be published tomorrow_
